;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="ItemType",DevComment="")
GameplayTagList=(Tag="ItemType.Ammo",DevComment="")
GameplayTagList=(Tag="ItemType.Heal",DevComment="")
GameplayTagList=(Tag="ItemType.Heal.Health",DevComment="")
GameplayTagList=(Tag="ItemType.Heal.Plate",DevComment="")
GameplayTagList=(Tag="ItemType.Weapon",DevComment="")
GameplayTagList=(Tag="ItemType.Weapon.MachineGun",DevComment="")
GameplayTagList=(Tag="ItemType.Weapon.PlasmaGun",DevComment="")

