;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="ID.PlasmaGun\\",NewTagName="ID.PlasmaGun")
+GameplayTagList=(Tag="AI_Test",DevComment="AI도 테스트 용도로 태그 쓸 수도 있제")
+GameplayTagList=(Tag="AI_Test.Complete.LongTerm",DevComment="")
+GameplayTagList=(Tag="AI_Test.Complete.ShortTerm",DevComment="")
+GameplayTagList=(Tag="AI_Test.Complete.TourPoint",DevComment="")
+GameplayTagList=(Tag="AITargetable",DevComment="AI의 대상이 될 수 있는 개체들의 목록")
+GameplayTagList=(Tag="AITargetable.Character",DevComment="")
+GameplayTagList=(Tag="AITargetable.DropItem",DevComment="")
+GameplayTagList=(Tag="AITargetable.DropItem.Ammo",DevComment="")
+GameplayTagList=(Tag="AITargetable.DropItem.Health",DevComment="")
+GameplayTagList=(Tag="AITargetable.DropItem.Plate",DevComment="")
+GameplayTagList=(Tag="AITargetable.DropItem.Weapon",DevComment="")
+GameplayTagList=(Tag="AITargetable.Spawner",DevComment="")
+GameplayTagList=(Tag="AITargetable.Spawner.Character",DevComment="")
+GameplayTagList=(Tag="AITargetable.Spawner.DropItem",DevComment="")
+GameplayTagList=(Tag="Buff",DevComment="")
+GameplayTagList=(Tag="Buff.Atk",DevComment="")
+GameplayTagList=(Tag="Buff.Def",DevComment="")
+GameplayTagList=(Tag="ID",DevComment="")
+GameplayTagList=(Tag="ID.HealPack",DevComment="")
+GameplayTagList=(Tag="ID.HealPack.Big",DevComment="")
+GameplayTagList=(Tag="ID.HealPack.Mega",DevComment="")
+GameplayTagList=(Tag="ID.HealPack.middle",DevComment="")
+GameplayTagList=(Tag="ID.HealPack.Small",DevComment="")
+GameplayTagList=(Tag="ID.MachineGun",DevComment="")
+GameplayTagList=(Tag="ID.MachineGun.Ammo",DevComment="")
+GameplayTagList=(Tag="ID.Pistol",DevComment="")
+GameplayTagList=(Tag="ID.PlasmaGun",DevComment="")
+GameplayTagList=(Tag="ID.PlasmaGun.Ammo",DevComment="")
+GameplayTagList=(Tag="ID.PlatePack",DevComment="")
+GameplayTagList=(Tag="ID.PlatePack.Big",DevComment="")
+GameplayTagList=(Tag="ID.PlatePack.Mega",DevComment="")
+GameplayTagList=(Tag="ID.PlatePack.middle",DevComment="")
+GameplayTagList=(Tag="ID.PlatePack.Small",DevComment="")
+GameplayTagList=(Tag="ID.Protection",DevComment="")
+GameplayTagList=(Tag="ID.QuadDamage",DevComment="")
+GameplayTagList=(Tag="ID.RailGun",DevComment="")
+GameplayTagList=(Tag="ID.RailGun.Ammo",DevComment="")
+GameplayTagList=(Tag="ID.RocketLauncher",DevComment="")
+GameplayTagList=(Tag="ID.RocketLauncher.Ammo",DevComment="")
+GameplayTagList=(Tag="ID.RocketLauncher.Projectile",DevComment="")
+GameplayTagList=(Tag="ID.ShotGun",DevComment="")
+GameplayTagList=(Tag="ID.ShotGun.Ammo",DevComment="")
+GameplayTagList=(Tag="ID.TeleportLauncher",DevComment="")
+GameplayTagList=(Tag="ID.TeleportLauncher.Sphere",DevComment="")
+GameplayTagList=(Tag="Item",DevComment="")
+GameplayTagList=(Tag="Item.Weapon",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.explosion",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.HitScan",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.Projectile",DevComment="")

